# permissions for end users to edit managers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: manager-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8
    app.kubernetes.io/part-of: k8
    app.kubernetes.io/managed-by: kustomize
  name: manager-editor-role
rules:
- apiGroups:
  - batch.k8.envsecrets.dev
  resources:
  - managers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.k8.envsecrets.dev
  resources:
  - managers/status
  verbs:
  - get
