---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.k8.envsecrets.dev
  resources:
  - managers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.k8.envsecrets.dev
  resources:
  - managers/finalizers
  verbs:
  - update
- apiGroups:
  - batch.k8.envsecrets.dev
  resources:
  - managers/status
  verbs:
  - get
  - patch
  - update
